version: "3.3"

services:

  plex:
    image: linuxserver/plex
    container_name: plex
    ports: 
      - "8200:32400" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
    volumes:
      - ./config:/config
      - ./tvseries:/tv
      - ./movies:/movies
      - ./media:/data 
    restart: unless-stopped